# Generated by Django 4.1.1 on 2022-09-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripback', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
